#!/bin/bash

echo

# Makes the cpu only operate at 400MHz to 800MHz
sudo cpupower frequency-set -d 400MHz -u 800Mhz

# Make the gpu only operate at 300MHz
echo 300 | sudo tee /sys/class/drm/card0/gt_min_freq_mhz
echo 300 | sudo tee /sys/class/drm/card0/gt_max_freq_mhz

echo
